config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :players
  resources :partidos do
    resources :players_lists do
      resources :lineups
    end
  end
  get '/json/getplayers', to: 'players_lists#get_players_json'

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lineup.rb
class Lineup < ApplicationRecord
end

app/models/partido.rb
class Partido < ApplicationRecord
  has_one :player_list
end

app/models/player.rb
class Player < ApplicationRecord
  has_and_belongs_to_many :player_lists
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/models/player_list.rb
class PlayerList < ApplicationRecord
  has_and_belongs_to_many :players
  belongs_to :partido
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  helper_method :current_user

  def authorize_user
    unless current_user
      flash[:message] = 'Please log in or register to access this page'
      redirect_to root_path
    end
  end

  def admin_only
    unless current_user && current_user.role == "admin"
      flash[:access_denied] = "Access denied. You must be admin in this page."
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index

  end
end

app/controllers/lineups_controller.rb
class LineupsController < ApplicationController
  def new
    @players_list= PlayerList.find_by(id: params[:players_list_id])
    @players=@players_list.players
  end
  def create
    my_partido = Partido.find_by(id: params[:partido_id])
    my_player_list = PlayerList.find_by(id: params[:players_list_id])
    players_list = Player.where(id: [params[:idPlayers]])
    my_partido.player_list.lineup = Lineup.new
    my_partido.player_list.lineup.players = players_list

    render json: { redirect_to: url_for(action: :index) }, status: :ok

  end

end

app/controllers/partidos_controller.rb
class PartidosController < ApplicationController
  def new
  end

  def index
    @partidos= Partido.all
  end

  def show
    @partido= Partido.find_by(id: params[:id])
    @playerslist = PlayerList.find_by(id: @partido.id)
  end

  def create
    partido = Partido.new(opponent: params[:opponent],
                      date: params[:date],
                      time: params[:time])
   if partido.save
     redirect_to partidos_path
   else
     redirect_to new_partido_path
   end
  end

  def edit
    @partido = Partido.find_by(id: params[:id])
  end

  def update
    partido = Partido.find_by(id: params[:id])
    partido.update(opponent: params[:opponent])
    partido.update(date: params[:date])
    partido.update(time: params[:time])

    redirect_to partidos_path
  end

  def destroy
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!

  def new
    @player = Player.new
  end

  def index
    @players= Player.all
  end

  def show
    @player= Player.find_by(id: params[:id])
  end

  def create

    @player = current_user.players.build(player_params)

   if @player.save
     redirect_to players_path
   else
     render 'new'
   end
  end

  def edit
    @player = Player.find_by(id: params[:id])
  end

  def update
    @player = Player.find_by(id: params[:id])

    if @player.update(player_params)
      redirect_to players_path
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def player_params
    params.require(:player).permit!
  end
end

app/controllers/players_lists_controller.rb
class PlayersListsController < ApplicationController
  def new
    @partido = Partido.find(params[:partido_id])
    @playerlist = PlayerList.new
    @players = Player.all
  end

  def get_players_json
      @players = Player.all
      render json: @players
  end

  def create
    my_partido = Partido.find_by(id: params[:partido_id])
    players_list = Player.where(id: [params[:idPlayers]])
    my_partido.player_list = PlayerList.new
    my_partido.player_list.players = players_list

    render json: { redirect_to: url_for(action: :index) }, status: :ok
  end

  def show
    @players = PlayerList.find_by(partido_id: params[:partido_id]).players
  end
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/convocatorias_helper.rb
module ConvocatoriasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lineups_helper.rb
module LineupsHelper
end

app/helpers/partidos_helper.rb
module PartidosHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/convocatorias/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Partidos :</h1>
    <ul>

      <%@players.each do |player| %>
      <li>
        <%= "#{player.nom} - #{player.cognom1}- #{player.posicio}" %>
      </li>
      <%end%>
    </ul>

  </body>
</html>

app/views/home/index.html.erb
    <img class='home-image' src="https://scontent.fmad3-1.fna.fbcdn.net/t31.0-8/s960x960/13731954_1049390615149464_2567667259990373448_o.jpg" alt="" />

app/views/layouts/_header.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Home', root_path%>
    </li>
    <li>
      <%= link_to 'Jugadores', players_path%>
    </li>

    <li>
      <%= link_to 'Nuevo Jugador', new_player_path%>
    </li>

    <li>
      <%= link_to 'Partidos', partidos_path%>
    </li>

    <li>
      <%= link_to 'Nuevo Partido', new_partido_path%>
    </li>

    <li>
      <%unless current_page? (new_user_session_path)%>
      <% if user_signed_in? %>
      <%= link_to 'Log out', destroy_user_session_path, method: 'DELETE'%>
      <% else %>
      <%= link_to 'Log in', new_user_session_path%>
      <% end %>
      <%end%>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QER</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <!-- <p class="notice"><%= notice %></p> -->
    <!-- <p class="alert"><%= alert %></p> -->


    <%= yield %>
  </body>
</html>

app/views/lineups/new.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script>
$(function(){
  $( ".draggable" ).draggable({
    containment: '#content',
    helper: 'clone',
    // stack: '#draggable div',
    cursor: 'move',
    revert: true
  });
});
</script>

<div class="row">
  <div class="container col-md-2" id='content'>
    <%@players.each do |player|%>
    <p class="draggable">
      name: <%=player.name%>
    </p>
    <% end %>
  </div>

    <div class='container col-md-10'>
      <div class="row" id='props'>
        <div class="col-md-1"></div>
        <div class="col-md-2 box" id='pos1'>hello</div>
        <div class="col-md-2"></div>
        <div class="col-md-2 box" id='pos2'></div>
        <div class="col-md-2"></div>
        <div class="col-md-2 box" id='pos3'></div>
        <div class="col-md-1"></div>
      </div>
      <div class="row" id='locks'>
        <div class="col-md-3"></div>
        <div class="col-md-2 box" id='pos3'></div>
        <div class="col-md-2"></div>
        <div class="col-md-2 box" id='pos3'></div>
        <div class="col-md-3"></div>
      </div>
      <div class="row" id='flankers'>
        <div class="col-md-1"></div>
        <div class="col-md-2 box" id='pos3'></div>
        <div class="col-md-2"></div>
        <div class="col-md-2 box" id='pos3'></div>
        <div class="col-md-2"></div>
        <div class="col-md-2 box" id='pos3'></div>
        <div class="col-md-1"></div>
      </div>
    </div>
  </div>
</div>

app/views/partidos/edit.html.erb
    <h1>Editar Perfil</h1>

    <%= form_tag(partido_path(@partido.id), :method=>'put') do %>

    <li>
      <%= label_tag :Rival%>
      <%= text_field_tag :opponent, @partido.opponent%>
    </li>

    <li>
      <%= label_tag :Fecha%>
      <%= text_field_tag :date, @partido.date%>
    </li>
    <li>
      <%= label_tag :Hora%>
      <%= text_field_tag :time, @partido.time%>
    </li>
    <li>
      <%= submit_tag "save"%>
    </li>
    <%end%>

app/views/partidos/index.html.erb
    <h1>Partidos :</h1>
    <ul>

      <%@partidos.each do |partido| %>
      <li>
        <%=link_to "- #{partido.opponent}: #{partido.date} - #{partido.time}", partido_path(partido.id), class: "text" %>
      </li>
      <%end%>
    </ul>

app/views/partidos/new.html.erb
    <%= form_tag('/partidos', :method=>'post') do %>
    <li>
      <%= label_tag :Rival%>
      <%= text_field_tag :opponent%>
    </li>
    <li>
      <%= label_tag :Fecha%>
      <%= date_field_tag :date%>
    </li>
    <li>
      <%= label_tag :Hora%>
      <%= time_field_tag :time%>
    </li>

    <li>
      <%= submit_tag "save"%>
    </li>
    <%end%>

app/views/partidos/show.html.erb
    <%if current_user.tipo_usuario == "admin"%>
    <%= link_to 'Editar', edit_partido_path%>
    <%end%>
    <%= link_to 'Partidos', partidos_path%>
    <%= link_to 'Convocatoria', new_partido_players_list_path(@partido.id, @playerslist.id)%>
    <li> Rival: <%=@partido.opponent%> </li>
    <li> Fecha: <%=@partido.date%> </li>
    <li> Hora:  <%=@partido.time%> </li>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
<li class='form'>
  <%= f.label :Nombre%>
  <%= f.text_field :name%>
</li>
<li class='form'>
  <%= f.label :Apellido1%>
  <%= f.text_field :lastname1%>
</li>
<li class='form'>
  <%= f.label :Apellido2%>
  <%= f.text_field :lastname2%>
</li>
<li class='form'>
  <%= f.label :Posición%>
  <%= f.text_field :position%>
</li>
<li class='form'>
  <%= f.label :Fecha_de_nacimiento%>
  <%= f.date_field :birthdate%>
</li>
<li class='form'>
  <%= f.file_field :avatar %>
</li>
<li>
  <%= f.submit "save"%>
</li>
<%end%>

app/views/players/edit.html.erb
    <h1>Editar Perfil</h1>
    <%= render partial: 'form' %>

app/views/players/index.html.erb
  <div class="main-container">
    <h1 class='title'>Jugadores :</h1>
    <ul>

      <%@players.each do |player| %>
      <li>
        <%if player.avatar.url%>
        <%= image_tag(player.avatar.url, :class => "index-image") %>
        <%end%>
        <%=link_to "- #{player.name}: #{player.lastname1} - #{player.position}", player_path(player.id), class: "text" %>
      </li>
      <%end%>
    </ul>
  </div>

app/views/players/new.html.erb
<div class="title-new-player">
  <h2>Añadir datos </h2>
</div>


<div class="container-centre">
<%= render partial: 'form' %>
  </div>

app/views/players/show.html.erb
    <div class="main-container">
      <h2 class="profile-title">Player profile</h2>
      <% if @player.avatar.url %>
        <div class="image-left">
          <%= image_tag(@player.avatar.url, :class => "profile-image") %>
        </div>
      <%end%>
      <div class="information-right">
        <p>
          Nom: <%=@player.name%>
        </p>
         <p>
           Primer Apellido: <%=@player.lastname1%>
         </p>
         <p>
           Segundo Apellido:  <%=@player.lastname2%>
         </p>
         <p>
           Posición: <%=@player.position%>
         </p>
         <p>
           Fecha de nacimeinto:  <%=@player.birthdate%>
         </p>
      </div>
    </div>

    <div class="link-to-edit">
      <%if current_user.id == @player.user_id%>
      <%= link_to 'Editar', edit_player_path%>
      <%end%>
    </div>

app/views/players_lists/index.html.erb
<%@players.each do |player|%>
  name: <%=player.name%>
<% end %>

app/views/players_lists/new.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script>
$(function() {
var ary = [];
var finalAry = [];

$('#PlayersList').html( '' );
// $('#FinalPlayers').html( '' );

$.ajax({
  type: 'GET',
  url: '/json/getplayers',
  success: function(response){
     for (var i = 0; i < response.length; i++) {
      ary.push(response[i]);
      // console.log(ary[i]);
    }
      SetPlayersLists();
      SetFinalPayers();
  },

  error: function(){
    console.log("error34")
  }
})

function SetPlayersLists(){
console.log(ary)
for ( var i=0; i<ary.length; i++ ) {
  $("<div class='potentialplayer' >" + ary[i].name + '</div>').data( 'number', ary[i].id ).attr( 'id', 'player'+ ary[i].id ).appendTo( '#PlayersList' ).draggable( {
    containment: '#content',
    helper: 'clone',
    stack: '#PlayersList div',
    cursor: 'move',
    revert: true
  } );
} }

// Create the card slots
function SetFinalPayers(){
  for ( var i=1; i<=23; i++ ) {
    $('#FinalPlayers').append($('<p>' +i+'</p>'))
    $("<div class='playerbox'></div>").data( 'number', i ).attr( 'id', 'box'+ i ).appendTo( '#FinalPlayers' ).droppable({
      accept: '#PlayersList div',
      drop: handlePlayerDrop
    });
  }
  $("<button type='button' class='savebutton' name='save'>Guardar</button>").appendTo( '#FinalPlayers' );
}

  function handlePlayerDrop(event, ui) {
    ui.draggable.position( { of: $(this), my: 'center', at: 'center' } );
    ui.draggable.draggable( 'option', 'revert', true );
    finalAry.push(ui.draggable.data('number'));
    console.log(finalAry);
  }

$('body').on('click', '.savebutton' , function(e) {
  e.preventDefault();
  console.log('dentro');
  console.log(finalAry);
  var partido_id = (window.location.href.split('/'))[4];
  console.log(partido_id);
  $.ajax({
    type: 'POST',
    url: 'http://localhost:3000/partidos/'+ partido_id +'/players_lists',
    data: {idPlayers: finalAry},
    success: function(response){
      console.log("success")
              window.location.href = response;
    },

    error: function(error){
      console.log(error)
    }
  })
})
})

</script>
<body>

<div id="content">
  <div class="row">
    <div class="col-md-5" id="PlayersList"></div>
    <div class="col-md-4" id="FinalPlayers"></div>
  </div>
</div>

</body>

app/views/players_lists/show.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script>
  var lineupAry = {};
$(function(){
  $( ".draggable" ).draggable({
    // containment: '#content',
    helper: 'clone',
    // stack: '#draggable div',
    cursor: 'move',
    revert: true
  });

  $('.box').droppable({
    accept: '.draggable',
    drop: handleDrop
  });

  function handleDrop(event, ui) {
    ui.draggable.position( { of: $(this), my: 'center', at: 'center' } );
    ui.draggable.draggable( 'option', 'revert', false );
    var position = $(this).attr('id');
    var player = ui.draggable.attr('id');
    lineupAry[position] = player
    console.log(lineupAry);

  }



  $('.lineupbutton').on('click', function(e) {
    e.preventDefault();
    console.log('dentro');
    console.log(lineupAry);
    var partido_id = (window.location.href.split('/'))[4];
    console.log(partido_id);
    var players_list_id = (window.location.href.split('/'))[6];
    console.log(players_list_id);
    $.ajax({
      type: 'POST',
      url: 'http://localhost:3000/partidos/'+ partido_id +'/players_lists'+players_list_id+'/lineups',
      data: {idPlayers: lineupAry},
      success: function(response){
        console.log("success")
                // window.location.href = response;
      },
  //
  //     error: function(error){
  //       console.log(error)
  //     }
    })
  })


});
</script>

<div class="row">
  <div class="container col-md-2" id='content'>
  <%@players.each do |player|%>
    <p class="draggable" id=<%=player.id%>>
      name: <%=player.name%>
    </p>
  <% end %>
  </div>
  <div class='container col-md-8'>
    <div class="row" id='props'>
      <div class="col-md-1"></div>
      <div class="col-md-2 box" id='pos1'></div>
      <div class="col-md-2"></div>
      <div class="col-md-2 box" id='pos2'></div>
      <div class="col-md-2"></div>
      <div class="col-md-2 box" id='pos3'></div>
      <div class="col-md-1"></div>
    </div>
    <div class="row" id='locks'>
      <div class="col-md-3"></div>
      <div class="col-md-2 box" id='pos4'></div>
      <div class="col-md-2"></div>
      <div class="col-md-2 box" id='pos5'></div>
      <div class="col-md-3"></div>
    </div>
    <div class="row" id='flankers'>
      <div class="col-md-1"></div>
      <div class="col-md-2 box" id='pos6'></div>
      <div class="col-md-2"></div>
      <div class="col-md-2 box" id='pos8'></div>
      <div class="col-md-2"></div>
      <div class="col-md-2 box" id='pos7'></div>
      <div class="col-md-1"></div>
    </div>
    <button type="button" class='lineupbutton' name="save">Guardar</button>
  </div>
</div>